---
title: "Raw Data"
author: "Olgiati Stefano (1)"
date: "21 May 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(1) Author Responsible For Correspondence: University of Bergamo <www.unibg.it>, Department of Quantitative Methods, via dei Caniana 2, Bergamo (ITA) 24129; tel  +39 035 20 52 638; fax +39 035 20 52 549; email <stefano.olgiati@unibg.it>

# Reading raw data in .csv format

```{r echo=FALSE}
library(data.table)

raw.data.GBD <- read.csv("GBD.csv")
raw.data.WHO.WF <- read.csv("WHO_WF.csv")
raw.data.WHO.THE <- read.csv("WHO_THE.csv")

names(raw.data.GBD)
names(raw.data.WHO.WF)
names(raw.data.WHO.THE)

head(raw.data.GBD)
head(raw.data.WHO.WF)
head(raw.data.WHO.THE)


dim(raw.data.GBD)
dim(raw.data.WHO.WF)
dim(raw.data.WHO.THE)


# Data Tables
attach(raw.data.GBD)
attach(raw.data.WHO.WF)
attach(raw.data.WHO.THE)

DT.GBD <- data.table(raw.data.GBD)
DT.WHO.WF <- data.table(raw.data.WHO.WF)
DT.WHO.THE <- data.table(raw.data.WHO.THE)

tables()
```


### Tidy Data Set

Manipulating data to generate tidy datasets
```{r}
# ISO3 codes of EU-28 Countries

# Austria, Belgium, Bulgaria, Croatia, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden and the UK

ISO3 <- c("AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA","DEU","GRC","HUN","IRL",
          "ITA","LVA","LTU","LUX","MLT","NLD","POL","PRT","ROU","SVK","SVN","ESP","SWE","GBR","USA")

length(ISO3) == 29


data.WHO.WF <- DT.WHO.WF[DT.WHO.WF$GHO..CODE. == "HRH_33" &
                                        DT.WHO.WF$COUNTRY..CODE. %in% ISO3, ]
df.WHO.spool <- data.frame(country=data.WHO.WF$COUNTRY..CODE., worforce=data.WHO.WF$Numeric, year=data.WHO.WF$YEAR..CODE.)
df.WHO.spool
df.WHO.WF <- df.WHO.spool[order(df.WHO.spool$country, abs(df.WHO.spool$year) ), ] 
#sort by country and reverse of abs(year)
df.WHO.WF <- df.WHO.WF[ !duplicated(df.WHO.WF$country), ]
df.WHO.WF
length(df.WHO.WF$country)
list(df.WHO.WF$country)

ISO3.revised <- as.vector(df.WHO.WF$country)
ISO3.revised
class(ISO3.revised)


data.GBD.2010 <- DT.GBD[DT.GBD$year == "2010" & DT.GBD$age_name == "0-1 years" &
                                DT.GBD$sex_name == "Both" & 
                                DT.GBD$iso3 %in% ISO3.revised , ]
data.GBD.2010.ordered <- data.GBD.2010[order(iso3), ]
data.GBD.2010.ordered




data.WHO.THE.2010 <- DT.WHO.THE[DT.WHO.THE$YEAR == "2010" & 
                                        DT.WHO.THE$GHO == "WHS7_105" & 
                                        DT.WHO.THE$Numeric != "NA" & 
                                        DT.WHO.THE$COUNTRY %in% ISO3.revised,  ]
data.WHO.THE.2010.ordered <- data.WHO.THE.2010[order(COUNTRY), ]
data.WHO.THE.2010.ordered


intermediate.data <- data.frame(country=data.GBD.2010.ordered$iso3, le=data.GBD.2010.ordered$le, hale=data.GBD.2010.ordered$hale, the=data.WHO.THE.2010.ordered$Numeric, worforce=df.WHO.WF$worforce)

intermediate.data

# Years Lived with Disability
yld <- intermediate.data$le - intermediate.data$hale
yld

# Tidy Dataset
tidy.data <- data.frame(country=data.GBD.2010.ordered$iso3, le=data.GBD.2010.ordered$le, hale=data.GBD.2010.ordered$hale, yld=yld, the=data.WHO.THE.2010.ordered$Numeric, worforce=df.WHO.WF$worforce)

tidy.data

attach(tidy.data)

# Saving Tidy Dataset to .csv file
write.csv(tidy.data, "Workforce_Output.csv")
```